config/routes.rb
Rails.application.routes.draw do
 
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :articles
  resources :categories
  resources :cities do
    match '/search' => 'cities#search', as: :search_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'cities#consult', as: :consult_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :companies do
    match '/search' => 'companies#search', as: :search_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'companies#consult', as: :consult_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :countries do
    match '/search' => 'countries#search', as: :search_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'countries#consult', as: :consult_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :doc_types do
    match '/search' => 'doc_types#search', as: :search_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'doc_types#consult', as: :consult_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditure_types do
    match '/search' => 'expenditure_types#search', as: :search_expenditure_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'expenditure_types#consult', as: :consult_expendityre_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditures
  resources :marks do
    match '/search' => 'marks#search', as: :search_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'marks#consult', as: :consult_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end

  resources :provinces do
    match '/search' => 'provinces#search', as: :search_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'provinces#consult', as: :consult_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :sales
  resources :turns
  resources :users do
    match '/search' => 'users#search', as: :search_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'users#consult', as: :consult_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  
  

  get "cities/search" => 'cities#search', :as => :cities_search

end

app/controllers/doc_types_controller.rb
class DocTypesController < ApplicationController
	def show

		@doc_type = DocType.find(params[:id])
	end

	def new 
		@doc_type = DocType.new
	end

	def create
		@doc_type = DocType.new(doc_type_params)
		if @doc_type.save
			flash[:success] = 'DocType added'
			redirect_to @doc_type
		else
			render 'new'
		end
	end

	def edit
		@doc_type = DocType.find(params[:id])
	end

	def update
		@doc_type = DocType.find(params[:id])
		if @doc_type.update_attributes(doc_type_params)
			flash[:success] = 'DocType updated'
			redirect_to @doc_type
		else
			render 'edit'
		end
	end

	def destroy
		DocType.find(params[:id]).destroy
		flash[:success] = 'DocType deleted'
		redirect_to countries_url
	end

	def index
		@doc_types = DocType.all
	end

	def search
		@doc_types  = DocType.order(:name).where("name LIKE ?","%#{params[:name]}%")
		doc_types = []
		@doc_types.each do |doc_type|
			doc_types << {id: doc_type.id,
					  	  name: doc_type.name
						 }
		end
		render json: doc_types.to_json
	end

	def consult
		@doc_type = DocType.find(params[:id])
		doc_type = []
		doc_type << {name:@doc_type.name}
		render json: doc_type.to_json
	end
	
	private
		def doc_type_params
			params.require(:doc_type).permit(:name)
		end
end

app/helpers/doc_types_helper.rb
module DocTypesHelper
end

app/views/doc_types/_select.html.erb
<%# Receiving the parameters from render invoke %>
<input type='hidden' id='return_place_<%=id%>' value='<%=return_place%>'></input>
<input type='hidden' id='id_<%=id%>' value='<%=id%>'></input>


<h4>Search by...</h4>
  <div class="input-group">
    <input type='text' id='search_field_<%=id%>' class='form-control' placeholder="Name">
    <span class="input-group-btn">
      <button type="button" class="btn btn-default" id='cancel_<%=id%>'>
        <span aria-hidden="true">×</span>
       </button>
    </span>
  </div>

<button id='search_<%=id%>' class='btn btn-primary form-control'>Search</button>

  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading"></div>

      <table class="table table-fixed">
      <thead>
        <tr>
          <th width="35%"></th>
          <th class="col-xs-4">Type</th>
        </tr>
      </thead> 
      <div id='scrollable' height='230px' overflow='auto' >
        <tbody id='table-body_<%=id%>'>
            <% @doc_types.each do |doc_type| %>
            <tr>
              <td class="col-xs-2">
                <button type="button" class="btn btn-info" data-dismiss="modal" onclick=listeningSelection_<%=id%>(<%= doc_type.id %>,"<%=return_place%>")>
                  <span class="glyphicon glyphicon-ok"></span> Select
                </button>
          
              </td>
              <td class="col-xs-4"><%= doc_type.name%></td>
            </tr>
            <% end %>


        </tbody>
      </div>
      </table>
  </div>

 

<script type="text/javascript">
  $('#cancel_<%=id%>').on('click',function(){
    $('#search_field_<%=id%>').val("");
    $('#search_<%=id%>').click();
  });


  $('#search_<%=id%>').on('click',function(){
    var val_s =  $('#search_field_<%=id%>').val();
    $.ajax({
      dateType:'json',
      url:'/doc_types/search',
      data: { name: val_s},
      method: 'POST'
    }).done(function(data){
      var res='';
      for (i=0;i<data.length;i++){
        res=res+'<tr >';
        res=res+'<td class="col-xs-2"><button type="button" class="btn btn-info" data-dismiss="modal" onclick=listeningSelection_'+$('#id_<%=id%>').val()+'('+data[i].id+',"'+$('#return_place_<%=id%>').val()+'")><span class="glyphicon glyphicon-ok"></span> Select</button></td>';
        res=res+'<td class="col-xs-4">'+data[i].name+'</td>';
        res=res+'</tr>';
      }
      $('#table-body_<%=id%>').html(res);
    });
  });

  function listeningSelection_<%=id%>(id,return_place){
    $('#'+return_place+'_id').val(id);                 //set id in hidden field 
    $.ajax({
      dateType:'json',
      url:'/doc_types/consult',
      data: { id: id},
      method: 'POST'
    }).done(function(data){
      $('#'+return_place+'_name').val(data[0].name);    // set name selected
    });
  }

</script>

app/views/doc_types/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit document type</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@doc_type) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
  	<%= f.label :name %>
  	<%= f.text_field :name %>

  	<%= f.submit "Edit documenet type", class: "btn btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/doc_types/new.html.erb
<% provide(:title, 'New') %>
<h1>New document type</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@doc_type) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
  	<%= f.label :name %>
  	<%= f.text_field :name %>

  	<%= f.submit "Create document type", class: "btn btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/doc_types/show.html.erb
<% provide(:title, @doc_type.name) %>

<h1><%=@doc_type.name%></h1>
<h3><span><%= link_to "Edit this document type", edit_doc_type_path %>-<%= link_to "Remove this document type", doc_type_path, method: "delete" %></span></h3>