config/routes.rb
Rails.application.routes.draw do
 
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :articles
  resources :categories
  resources :cities do
    match '/search' => 'cities#search', as: :search_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'cities#consult', as: :consult_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :companies do
    match '/search' => 'companies#search', as: :search_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'companies#consult', as: :consult_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :countries do
    match '/search' => 'countries#search', as: :search_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'countries#consult', as: :consult_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :doc_types do
    match '/search' => 'doc_types#search', as: :search_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'doc_types#consult', as: :consult_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditure_types do
    match '/search' => 'expenditure_types#search', as: :search_expenditure_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'expenditure_types#consult', as: :consult_expendityre_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditures
  resources :marks do
    match '/search' => 'marks#search', as: :search_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'marks#consult', as: :consult_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end

  resources :provinces do
    match '/search' => 'provinces#search', as: :search_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'provinces#consult', as: :consult_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :sales
  resources :turns
  resources :users do
    match '/search' => 'users#search', as: :search_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'users#consult', as: :consult_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  
  

  get "cities/search" => 'cities#search', :as => :cities_search

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :city
  has_many :article_company_relationships
  has_many :articles, through: :article_company_relationships

  validates :name, presence: true, length: { maximum: 50 }
  validates :city_id, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, format:{ with: VALID_EMAIL_REGEX }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	def show
		@company = Company.find(params[:id])
	end

	def new
		@company = Company.new
		@cities  = City.order(:name).all
	end

	def create
		@company = Company.new(company_params)
		if @company.save
			flash[:success] = 'Company created'
			redirect_to @company
		else
			@cities = City.order(:name).all
			render 'new'
		end
	end

	def edit
		@company = Company.find(params[:id])
		@cities  = City.order(:name).all
	end

	def update
		@company = Company.find(params[:id])
		if @company.update_attributes(company_params)
			flash[:success] = 'Company updated'
			redirect_to @company
		else
			@cities = City.order(:name).all
			render 'edit'
		end
	end

	def destroy
		Company.find(params[:id]).destroy
		flash[:success] = 'Company deleted'
		redirect_to companies_url
	end

	def index
		@companies = Company.all
	end

	def search 
		@companies  = Company.order(:name).where("name LIKE ?","%#{params[:name]}%")
		companies = []
		@companies.each do |company|
			companies << {id: company.id,
					  name: company.name
							 }
		end
		render json: companies.to_json
	end

	def consult
		@company = Company.find(params[:id])
		company = []
		company << {name:@company.name}
		render json: company.to_json
	end


	private
		def company_params
			params.require(:company).permit(:name,:cuit,:street,:number,
											:floor,:apartment,:city_id,
											:fixed_tel,:cel_tel,:email,
											:description)
		end
end

app/helpers/companies_helper.rb
module CompaniesHelper

	
end

app/views/companies/_multiple_select.html.erb
<%# Receiving the parameters from render invoke %>
<input type='hidden' id='return_place_<%=id%>' value='<%=return_place%>'></input>
<input type='hidden' id='id_<%=id%>' value='<%=id%>'></input>

<h4>Search by...</h4>
  <div class="input-group">
    <input type='text' id='search_field_<%=id%>' class='form-control' placeholder="Name">
    <span class="input-group-btn">
      <button type="button" class="btn btn-default" id='cancel_<%=id%>'>
        <span aria-hidden="true">×</span>
       </button>
    </span>
  </div>

<button id='search_<%=id%>' class='btn btn-primary form-control'>
<span class="glyphicon glyphicon-search"></span> Search
</button>

  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading"></div>
      <a href=""><h4 id='counter' align="center">Selected items(0)</h4></a>
      <table class="table table-fixed">
      <thead>
        <tr>
          <th width="35%"></th>
          <th class="col-xs-4">Provider company</th>
        </tr>
      </thead> 
      <div id='scrollable' height='230px' overflow='auto' >
        <tbody id='table-body_<%=id%>'>
            <% @companies.each do |company| %>
            <tr id='tr_<%= company.id %>' >
              <td class="col-xs-2">
                <button type="button" class="btn btn-info" onclick=listeningSelection_<%=id%>(<%= company.id %>,"<%=return_place%>")>
                  <span class="glyphicon glyphicon-ok"></span> Select
                </button>
          
              </td>
              <td class="col-xs-4"><%= company.name%></td>
            </tr>
            <% end %>
        </tbody>
      </div>
      </table>
  </div>

<button id='confirm_<%=id%>' class='btn btn-success form-control' onclick=confirm_<%=id%>("<%=return_place%>") data-dismiss="modal">
<span class="glyphicon glyphicon-ok"></span> Confirm
</button>

 

<script type="text/javascript">

  var selected_items = [];
  
  $('#cancel_<%=id%>').on('click',function(){
    $('#search_field_<%=id%>').val("");
    $('#search_<%=id%>').click();
  });

  $('#search_<%=id%>').on('click',function(){
    var val_s =  $('#search_field_<%=id%>').val();
    $.ajax({
      dateType:'json',
      url:'/companies/search',
      data: { name: val_s},
      method: 'POST'
    }).done(function(data){
      var res='';
      for (i=0;i<data.length;i++){
        var aux = selected_items.indexOf(data[i].id);
        if (aux != -1){

          res=res+'<tr id="tr_'+data[i].id+'" class="hvr">';
          res=res+'<td class="col-xs-2"><button type="button" class="btn btn-info" onclick=listeningSelection_'+$('#id_<%=id%>').val()+'('+data[i].id+',"'+$('#return_place_<%=id%>').val()+'")><span class="glyphicon glyphicon-ok"></span> Select</button></td>';
          res=res+'<td class="col-xs-4">'+data[i].name+'</td>';
          res=res+'</tr>';
        }else{
          res=res+'<tr id="tr_'+data[i].id+'">';
          res=res+'<td class="col-xs-2"><button type="button" class="btn btn-info" onclick=listeningSelection_'+$('#id_<%=id%>').val()+'('+data[i].id+',"'+$('#return_place_<%=id%>').val()+'")><span class="glyphicon glyphicon-ok"></span> Select</button></td>';
          res=res+'<td class="col-xs-4">'+data[i].name+'</td>';
          res=res+'</tr>';
        }
      }
      $('#table-body_<%=id%>').html(res);
    });
  });

  

  function listeningSelection_<%=id%>(id,return_place){
    //selected_items.push(id);
    var aux = selected_items.indexOf(id);
    ;
    if (aux == -1){
      //item not found in array
      selected_items.push(id);
      $('#tr_'+id.toString()).attr('class','hvr');
    }else{
      selected_items.splice(aux,1);
       $('#tr_'+id.toString()).attr('class','');
    }
    
    $('#counter').html('Selected items('+selected_items.length+')');
    //$('#'+return_place+'_id').val(id);                  //set id in hidden field 
    /*$.ajax({
      dateType:'json',
      url:'/marks/consult',
      data: { id: id},
      method: 'POST'
    }).done(function(data){
      $('#'+return_place+'_name').val(data[0].name);    // set name selected
    });
    */
  }

  function confirm_<%=id%>(return_place){
    $('#'+return_place).val(selected_items.toString());
    alert(return_place);
    
  

  }

</script>

app/views/companies/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit company</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@company) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :cuit %>
      <%= f.text_field :cuit %>

      <%= f.label :street %>
      <%= f.text_field :street %>

      <%= f.label :number %>
      <%= f.text_field :number %>

      <%= f.label :floor %>
      <%= f.number_field :floor %>

      <%= f.label :apartment %>
      <%= f.text_field :apartment %>

      <%= f.label :city_id %> 
      <div class="input-group">
        <%= f.hidden_field :city_id %>
        <% if @company.city!=nil %>
          <input type='text' id='company_city_name' value='<%= @company.city.name %>' class='form-control' disabled></input>
          
        <%else%>
           <input type='text' id='company_city_name' class='form-control' disabled></input>
        <%end%>
        <span class="input-group-btn">
           <button type="button" class="btn btn-info" data-toggle="modal" data-target="#popup-city">
            <span class="glyphicon glyphicon-search"></span> Search
           </button>
        </span>
      </div>


      <%= f.label :fixed_tel %>
      <%= f.text_field :fixed_tel %>

      <%= f.label :cel_tel %>
      <%= f.text_field :cel_tel %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Edit company", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div id='city_popup'>
  <%= render :partial => 'shared/popup', :locals => {:id =>'city', :popup_title => 'Select a city',:popup_form =>'cities/select', :return_place =>'company_city'} %>
</div>

app/views/companies/new.html.erb
<% provide(:title, 'New') %>
<h1>New company</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@company) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :cuit %>
      <%= f.text_field :cuit %>

      <%= f.label :street %>
      <%= f.text_field :street %>

      <%= f.label :number %>
      <%= f.text_field :number %>

      <%= f.label :floor %>
      <%= f.number_field :floor %>

      <%= f.label :apartment %>
      <%= f.text_field :apartment %>

      <%= f.label :city_id %> 
      <div class="input-group">
        <%= f.hidden_field :city_id %>
        <% if @company.city!=nil %>
          <input type='text' id='company_city_name' value='<%= @company.city.name %>' class='form-control' disabled></input>
          
        <%else%>
           <input type='text' id='company_city_name' class='form-control' disabled></input>
        <%end%>
        <span class="input-group-btn">
           <button type="button" class="btn btn-info" data-toggle="modal" data-target="#popup-city">
            <span class="glyphicon glyphicon-search"></span> Search
           </button>
        </span>
      </div>


      <%= f.label :fixed_tel %>
      <%= f.text_field :fixed_tel %>

      <%= f.label :cel_tel %>
      <%= f.text_field :cel_tel %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Create company", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div id='city_popup'>
  <%= render :partial => 'shared/popup', :locals => {:id =>'city', :popup_title => 'Select a city',:popup_form =>'cities/select', :return_place =>'company_city'} %>
</div>

app/views/companies/show.html.erb
<% provide(:title, @company.name) %>
<h1><%= @company.name %></h1>
<h3><span><%= link_to "Edit this company", edit_company_path %>-<%= link_to "Remove this company", company_path, method: "delete" %></span></h3>