config/routes.rb
Rails.application.routes.draw do
 
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :articles
  resources :categories
  resources :cities do
    match '/search' => 'cities#search', as: :search_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'cities#consult', as: :consult_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :companies do
    match '/search' => 'companies#search', as: :search_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'companies#consult', as: :consult_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :countries do
    match '/search' => 'countries#search', as: :search_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'countries#consult', as: :consult_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :doc_types do
    match '/search' => 'doc_types#search', as: :search_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'doc_types#consult', as: :consult_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditure_types do
    match '/search' => 'expenditure_types#search', as: :search_expenditure_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'expenditure_types#consult', as: :consult_expendityre_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditures
  resources :marks do
    match '/search' => 'marks#search', as: :search_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'marks#consult', as: :consult_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end

  resources :provinces do
    match '/search' => 'provinces#search', as: :search_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'provinces#consult', as: :consult_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :sales
  resources :turns
  resources :users do
    match '/search' => 'users#search', as: :search_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'users#consult', as: :consult_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  
  

  get "cities/search" => 'cities#search', :as => :cities_search

end

app/models/category.rb
class Category < ActiveRecord::Base
	
	has_many :article_category_relationships
	has_many :articles, through: :article_category_relationships

	validates :name, presence: true, length: { maximum: 50 }

	def has_articles?
		self.articles == nil
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = 'Category created'
			redirect_to @category
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(category_params)
			flash[:success] = 'Category updated'
			redirect_to @category
		else
			render 'edit'
		end
	end

	def destroy
		Category.find(params[:id]).destroy
		flash[:success] = 'Category deleted'
		redirect_to categories_url
	end

	def index
		@categories = Category.all
	end
	private
		def category_params
			params.require(:category).permit(:name)
		end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit article</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@category) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
  	<%= f.label :name %>
  	<%= f.text_field :name %>

  	<%= f.submit "Update category", class: "btn btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/categories/index.html.erb
index

app/views/categories/new.html.erb
<% provide(:title, 'New') %>
<h1>New category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@category) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
  	<%= f.label :name %>
  	<%= f.text_field :name %>

  	<%= f.submit "Create category", class: "btn btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>
<h1><%= @category.name %></h1>
<h3><span><%= link_to "Edit this category", edit_category_path %>-<%= link_to "Remove this cateogory", category_path, method: "delete" %></span></h3>