config/routes.rb
Rails.application.routes.draw do
 
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :articles
  resources :categories
  resources :cities do
    match '/search' => 'cities#search', as: :search_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'cities#consult', as: :consult_city, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :companies do
    match '/search' => 'companies#search', as: :search_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'companies#consult', as: :consult_company, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :countries do
    match '/search' => 'countries#search', as: :search_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'countries#consult', as: :consult_country, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :doc_types do
    match '/search' => 'doc_types#search', as: :search_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'doc_types#consult', as: :consult_doc_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditure_types do
    match '/search' => 'expenditure_types#search', as: :search_expenditure_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'expenditure_types#consult', as: :consult_expendityre_type, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :expenditures
  resources :marks do
    match '/search' => 'marks#search', as: :search_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'marks#consult', as: :consult_mark, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end

  resources :provinces do
    match '/search' => 'provinces#search', as: :search_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'provinces#consult', as: :consult_province, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  resources :sales
  resources :turns
  resources :users do
    match '/search' => 'users#search', as: :search_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
    match '/consult' => 'users#consult', as: :consult_user, via:[:get,:post], on: :collection, :defaults => {:format => 'json'}
  end
  
  

  get "cities/search" => 'cities#search', :as => :cities_search

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :user

  has_many :article_sale_relationships
  has_many :article, through: :article_sale_relationships

  validates :amount, presence: true
  validates :date, presence: true
  validates :user_id, presence: true
  def has_articles?
  	self.articles != nil
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

	def show
		@sale = Sale.find(params[:id])
	end

	def new
		@sale = Sale.new
		@users= User.order(:name).all
	end

	def create
		@sale = Sale.new(sale_params)
		if @sale.save
			flash[:success] = 'Sale added'
			redirect_to @sale
		else
			@users= User.order(:name).all
			render 'new'
		end
	end

	def edit
		@sale = Sale.find(params[:id])
		@users= User.order(:name).all
	end

	def update 
		@sale = Sale.find(params[:id])
		if @sale.update_attributes(sale_params)
			flash[:success] = 'Sale updated'
			redirect_to @sale
		else
			@users= User.order(:name).all
			render 'edit'
		end
	end

	def destroy
		Sale.find(params[:id]).destroy
		flash[:success] = 'Sale deleted'
		redirect_to sales_url
	end

	def index
		@sales = Sale.all
	end

	private
		def sale_params
			params.require(:sale).permit(:amount,:date,:user_id)
		end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit sale</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@sale) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
  	<%= f.label :amount %>
  	<%= f.number_field :amount %>

  	<%= f.label :date %>
  	<%= f.date_field :date %>

    <%= f.label :user_id %> 
    <div class="input-group">
      <%= f.hidden_field :user_id %>
      <% if @sale.user!=nil %>
        <input type='text' id='sale_user_name' value='<%= @sale.user.name %>' class='form-control' disabled></input>
        
      <%else%>
         <input type='text' id='sale_user_name' class='form-control' disabled></input>
      <%end%>
      <span class="input-group-btn">
         <button type="button" class="btn btn-info" data-toggle="modal" data-target="#popup-user">
          <span class="glyphicon glyphicon-search"></span> Search
         </button>
      </span>
    </div>

  	<%= f.submit "Update sale", class: "btn btn-primary" %>
  	<% end %>
  </div>
</div>


<div id='user_popup'>
  <%= render :partial => 'shared/popup', :locals => {:id =>'user' ,:popup_title => 'Select a user',:popup_form =>'users/select', :return_place =>'sale_user'} %>
</div>

app/views/sales/new.html.erb
<% provide(:title, 'New') %>
<h1>New sale</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@sale) do |f| %>
  	<%= render 'shared/error_messages', object: f.object %>
  	<%= f.label :amount %>
  	<%= f.number_field :amount %>

  	<%= f.label :date %>
  	<%= f.date_field :date %>

    <%= f.label :user_id %> 
    <div class="input-group">
      <%= f.hidden_field :user_id %>
      <% if @sale.user!=nil %>
        <input type='text' id='sale_user_name' value='<%= @sale.user.name %>' class='form-control' disabled></input>
        
      <%else%>
         <input type='text' id='sale_user_name' class='form-control' disabled></input>
      <%end%>
      <span class="input-group-btn">
         <button type="button" class="btn btn-info" data-toggle="modal" data-target="#popup-user">
          <span class="glyphicon glyphicon-search"></span> Search
         </button>
      </span>
    </div>
  	<%= f.submit "Create sale", class: "btn btn-primary" %>
  	<% end %>
  </div>
</div>

<div id='user_popup'>
  <%= render :partial => 'shared/popup', :locals => {:id =>'user' ,:popup_title => 'Select a user',:popup_form =>'users/select', :return_place =>'sale_user'} %>
</div>

app/views/sales/show.html.erb
<% provide(:title, 'Sale') %>

<h1><%=@sale.amount%></h1>
<h3><span><%= link_to "Edit this sale", edit_sale_path %>-<%= link_to "Remove this sale", sale_path, method: "delete" %></span></h3>